#!/usr/bin/env bash

CERT1=$1
CERT2=$2

if ! which openssl >/dev/null; then
    # OpenSSL binary doesn't exists
    echo "It looks like the 'openssl' command does not exist on your system, or you don't have access to it."
    echo "Install it first to use this tool."
    echo "  on Red Hat / CentOS: yum install openssl"
    echo "  on Ubuntu / Debian: apt-get install openssl"
    exit 1
fi

if [ "${CERT1}" == "${CERT2}" ]; then
    echo "It looks like you're trying to diff the same file, are you sure that's right? They should be the same."
    exit 1
fi

# Read the certificates and write to a temporary location
CERT_INFO='openssl x509 -subject -issuer -dates -alias -noout'
CERT1_OUT=$(${CERT_INFO} -in ${CERT1} 2>/dev/null)
if [ $? -ne 0 ]; then
    echo "Could not accurately parse the first parameter ($CERT1). Is this a real certificate?"
    echo "The following should return certificate info:"
    echo "$ openssl x509 -text -noout -in $CERT1"
    exit 1
fi

CERT2_OUT=$(${CERT_INFO} -in ${CERT2} 2>/dev/null)
if [ $? -ne 0 ]; then
    echo "Could not accurately parse the second parameter ($CERT1). Is this a real certificate?"
    echo "The following should return certificate info:"
    echo "$ openssl x509 -text -noout -in $CERT2"
    exit 1
fi

# Diff the results
DIFF=$(diff -y <(echo "${CERT1_OUT}") <(echo "${CERT2_OUT}"))
if [ $? -ne 0 ]; then
    echo "${DIFF}"
else
    echo "No differences, the data (FQDN, SAN, ...) is the same."
fi
